[package]
name = "stremio-state-ng"
version = "0.1.0"
authors = ["Ivo Georgiev <ivo@strem.io>"]
edition = "2018"

[dependencies]
serde = "1.0.42"
serde_derive = "1.0.42"
serde_json = "1.0.16"
#vtt = { git = "https://github.com/Ivshti/vtt.git" }

[dev-dependencies]
reqwest = "0.9.x"
