[package]
name = "stremio-state-ng"
version = "0.1.0"
authors = ["Ivo Georgiev <ivo@strem.io>"]
edition = "2018"

[dependencies]
serde = { version ="1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
serde_json = "1.0"
#vtt = { git = "https://github.com/Ivshti/vtt.git" }
futures = "0.1.x"
http = "0.1"

[dev-dependencies]
reqwest = "0.9.x"
tokio = "0.1"
