name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Init git submodules
      run: git submodule update --init --recursive
    - name: Test
      run: cargo test unit_tests -- --test-threads=1
