name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Server
      run: |
        curl https://s3-eu-west-1.amazonaws.com/stremio-artifacts/four/master/server.js > ./server.js
        node server.js &
    - name: Checkout Test Addon
      uses: actions/checkout@v2
      with:
        repository: Stremio/stremio-test-addon
        path: stremio-test-addon
    - name: Run Test Addon
      run: |
        cd stremio-test-addon
        yarn install
        yarn start --delay 1 --error 0 --port 7001 &
    - name: Test
      run: cargo test
