name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init git submodules
      run: git submodule update --init --recursive
    - name: Install rust toolchain
      run: rustup toolchain install 1.45.0
    - name: Set default rust toolchain
      run: rustup default 1.45.0
    - name: Test
      run: cargo test unit_tests -- --test-threads=1
